# ~/.config/zsh/rc

bindkey -v
setopt autocd

# history
HISTFILE=~/.cache/zsh/history
HISTSIZE=1000
SAVEHIST=1000
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_REDUCE_BLANKS

# up/down search
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
source ~/.config/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

# completion
autoload -Uz compinit
compinit -d ~/.cache/zsh/zcompdump
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'

# extra
source ~/.config/zsh/aliases
source ~/.config/zsh/keys
