" Disable vi mode
set nocompatible

" environment
set nobackup
set noswapfile
set viminfo+=n~/.cache/vim/info
set autochdir

" visuals
syntax on

" fixes
" fix delay to return to normal mode
set ttimeoutlen=5
" fix filetypes with #comments
autocmd FileType yaml,python setlocal indentkeys-=0#
" i forgot what this does
" set timeoutlen=1000

" line numbers
set number
" number of lines buffer from edge
set scrolloff=16
" disable line wrap
set nowrap
" auto switch relative<->absolute line numbers
:augroup numbertoggle
:  autocmd!
:  autocmd BufEnter,FocusGained,InsertLeave,WinEnter * if &nu && mode() != "i" | set relativenumber   | endif
:  autocmd BufLeave,FocusLost,InsertEnter,WinLeave   * if &nu                  | set norelativenumber | endif
:augroup END

" whitespace
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set autoindent
set smartindent
set smarttab
set listchars=tab:→\ ,trail:·
set list

" code folding
" globals: 'zm' / 'zr'
" locals: 'zc' / 'zo'
set foldmethod=syntax
" always show folding indicator column
set foldcolumn=1
" folding enabled but always start with no folding
" https://superuser.com/questions/567352/how-can-i-set-foldlevelstart-in-vim-to-just-fold-nothing-initially-still-allowi
:autocmd BufWinEnter * let &foldlevel = max(map(range(1, line('$')), 'foldlevel(v:val)'))

" search
nnoremap / /\v
vnoremap / /\v
set ignorecase
set smartcase
set gdefault
set incsearch
set showmatch
set hlsearch
set wildmenu

" more
source ~/.config/vim/netrw.vim
source ~/.config/vim/tabs.vim
source ~/.config/vim/keybindings.vim
