# $HOME/.config/starship.toml

format = """\
$username$hostname$directory$git_branch$symbol( $git_commit$git_status$git_metrics$git_state)\
$fill$cmd_duration$all\
$character"""

[aws]
disabled=true

[gcloud]
disabled=true

[fill]
symbol=" "

[username]
format='[$user]($style) at '

[hostname]
trim_at=''
format='[$ssh_symbol$hostname]($style) in '

[golang]
symbol=' '
format='[$symbol$version]($style) '
style='bold cyan'

[nodejs]
format=' [$symbol$version]($style)'

[ruby]
format=' [$symbol$version]($style)'

[cmd_duration]
min_time = 250
format = "[  $duration ]($style)"

[git_status]
format = "[($ahead_behind$stashed)]($style) "
style = "cyan"
stashed = "≡"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
